services:
  - type: web
    name: invoice-manager
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -c "from app import app, db; db.create_all(app=app)" && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
